name: Create Release

on:
  push:
    tags:
      - 'v*'  # Triggers the workflow when a tag starting with 'v' is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Add explicit permission for creating releases
    permissions:
      contents: write

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Prepare Release Directory
      - name: Prepare Release Directory
        run: |
          # Remove LossPunishment directory if it already exists
          rm -rf LossPunishment
          
          # Create a fresh LossPunishment directory
          mkdir -p LossPunishment
          
          # Copy addon files to the release directory
          cp Core.lua LossPunishment/
          cp Logo.blp LossPunishment/
          cp UI.lua LossPunishment/
          cp Options.lua LossPunishment/
          cp LossPunishment.toc LossPunishment/
          cp README.md LossPunishment/ || echo "No README.md found"
          cp LICENSE LossPunishment/ || echo "No LICENSE file found"
          # Update copyright year in LICENSE file if it exists
          if [ -f LossPunishment/LICENSE ]; then
            sed -i "s/Copyright (c) [0-9]* Frikk Jarl/Copyright (c) 2024 Frikk Jarl/" LossPunishment/LICENSE
          fi
          # Copy any additional library folders if they exist
          # cp -r LibStub LossPunishment/ || echo "No LibStub folder found"

      # Step 3: Zip Release Files
      - name: Zip Release Files
        run: |
          zip -r LossPunishment.zip LossPunishment  # Zip the 'LossPunishment' directory to include it in the archive

      # Step 4: Create GitHub Release and Upload Asset
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: LossPunishment.zip
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 